### ISSUE TITLE
Convert AWS code to use Terragrunt

### ISSUE THREAD

**Issue by ejaxon** [cityofasheville/bedrock2#40]
Here are some helpful articles:

- https://www.bti360.com/organizing-terraform-code-with-terragrunt/
- https://medium.com/rockedscience/hard-lessons-from-deploying-lambda-functions-with-terraform-4b4f98b8fc39
- [Sample Terragrunt deployment setup](https://github.com/cityofasheville/acumen-interface/tree/development/deploy/enterprise)
-

**Comment by bitslayer42** [comment]
I tried to distill what I understand about the way Nancie was using Terragrunt into a template here: 

-  https://github.com/cityofasheville/terragrunt-template

May or may not be useful.
